# Generated by Django 3.0.1 on 2020-03-13 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pistol',
            fields=[
                ('high', models.FloatField(blank=True, null=True)),
                ('low', models.FloatField(blank=True, null=True)),
                ('opened', models.FloatField(blank=True, null=True)),
                ('closed', models.FloatField(blank=True, null=True)),
                ('rangee', models.FloatField(blank=True, null=True)),
                ('msf', models.FloatField(blank=True, db_column='MSF', null=True)),
                ('jgd', models.FloatField(blank=True, db_column='JGD', null=True)),
                ('jwd', models.FloatField(blank=True, db_column='JWD', null=True)),
                ('sr', models.AutoField(db_column='Sr', primary_key=True, serialize=False)),
                ('directors_pattern', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'pistol',
                'managed': False,
            },
        ),
    ]
